### ISSUE TITLE
Orders template

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#1]
Orders are viewable in the wagtail admin, but it is not particularly useful atm. 
We could customise the admin template to allow:

- A button to fufill orders
- Full view of foreign key relationships (i.e. shipping address)

**Comment by alexfromvl** [comment]
I think the best solution is to create a dashboard, which will be the main information about the store, including the orders.

**Comment by JamesRamm** [comment]
I agree a dashboard would be a great place to eventually take it, although this will probably take more than one issue to complete..We would need other potentially useful modules such as analytics, customers etc. 
The suggestion does open up one interesting avenue which may be to start off by dropping the standard `ModelAdmin` templates completely and designing from scratch, since a dashboard would probably necessitate that anyway (I dont think wagtail has any particular support for this use case - we should ask a wagtail developer to confirm).

It also reminds me that adding/editing shipping rates is also something that needs to be addressed; there is currently only the model.

**Comment by JamesRamm** [comment]
The changes being discussed here: https://github.com/wagtail/wagtail/issues/3336 would probably be beneficial for this...

**Comment by alexfromvl** [comment]
The basis for the development of the dashboard suggest getting the wagtailadmin base template, add to it the necessary function. I did the pr with a basic template modeladmin/orders for development.

**Comment by JamesRamm** [comment]
Hi
Thanks for the pull request.
Since the `Order` model is a standard django model (rather than inheriting from `Page`), I was planning on using the `ModelAdmin` wagtail app, which will register generic models. See the 'order_template' branch for work I have done here. 
With `ModelAdmin`, we can use the existing views (e.g IndexView) and just provide a better `Detail` view which allows fulfillment/refund/any other actions. 
In the order_template branch, I have supplied such a template and work necessary to register it with `ModelAdmin` - I just need to provide handlers for the buttons then will make a pull request.
The front end for this view is written using react, which does add more work to the initial setup of longclaw for development, but it will make long term development and dynamic pages easier (hopefully). 

If I understand correctly, your approach is the start of a more thorough overhaul overriding the root admin page itself?

**Comment by JamesRamm** [comment]
PR #15 should cover enough to close this issue. I think #14 which (if I understand) is the start of addressing a more general dashboard, might be more suited to a separate issue?

**Comment by JamesRamm** [comment]
@alexfromvl, could you (if still interested) open a separate issue to address your dashboard idea and current work on your PR?

**Comment by alexfromvl** [comment]
@JamesRamm Ok.
