### ISSUE TITLE
Good day!

### ISSUE THREAD

**Issue by Wladislav** [JamesRamm/longclaw#124]
Help me pls, how i can add in product index class images?
I try do this (products/model.py):

class ShopProductIndex(Page):
    subpage_types = ('longclawproducts.Product', 'products.ShopProductIndex')
    
    content_panels = Page.content_panels + [
        InlinePanel('images', label='Product index images'),
    ]

    @property
    def first_image(self):
        return self.images.first()
   
class ProductIndexImage(Orderable):

    product = ParentalKey(ShopProductIndex, related_name='images')
    image = models.ForeignKey('wagtailimages.Image', on_delete=models.CASCADE, related_name='+')
    caption = models.CharField(blank=True, max_length=255)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption')
    ]

But i have 2 variant product index in wagtal admin. I want use only one
![image](https://user-images.githubusercontent.com/2454823/34454110-72d941e0-ed74-11e7-86e7-2a2ce03728a7.png)

**Comment by Wladislav** [comment]
Sorry, I figured it out.

**Comment by JamesRamm** [comment]
That's great! Sorry for the delay (Christmas and all) glad you figured it out

**Comment by Wladislav** [comment]
So far, nothing better came up, except to take your project into own and change its code. (monkey patching)
