### ISSUE TITLE
url longclaw_basket occur error

### ISSUE THREAD

**Issue by Wladislav** [JamesRamm/longclaw#128]
* longclaw version: last
* Django version:  (1, 10, 8, 'final', 0)
* Python version: 3.6.4

When paste in template` {% url 'longclaw_basket' %}`
`Error: Reverse for 'longclaw-basket' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []`

How fix it?

**Comment by JamesRamm** [comment]
@Wladislav 
You need to make sure you have a template for the basket. This should be in `longclawbasket/basket.html` in your templates directory.
Relevant docs: 
http://longclaw.readthedocs.io/en/latest/walkthrough/basket.html

**Comment by JamesRamm** [comment]
Closing - Can't reproduce
