### ISSUE TITLE
invalid REST IP call

### ISSUE THREAD

**Issue by Wladislav** [JamesRamm/longclaw#129]
### need some change in code in \longclaw\longclawbasket\api.py

    def destroy(self, request, variant_id=None):
        '''
        Remove an item from the basket
        '''
        variant = ProductVariant.objects.get(id=variant_id)
        # quantity = request.data.get("quantity", 1) always return 1
        # need call request.query_params.get for like /api/basket/2/?quantity=3
        quantity_str = request.query_params.get('quantity', 1)
        try:
            quantity = int(quantity_str)
        except ValueError:
            quantity = 1

        try:
            item = BasketItem.objects.get(
                basket_id=utils.basket_id(request), variant=variant)
            item.decrease_quantity(quantity)
        except BasketItem.DoesNotExist:
            pass

        serializer = BasketItemSerializer(self.get_queryset(request), many=True)
        return Response(data=serializer.data,
                        status=status.HTTP_200_OK)

**Comment by JamesRamm** [comment]
Hi, can you describe the problem you are having?

**Comment by Wladislav** [comment]
i can not delate from basket more then 1 product
// DELATE ITEM CART
function DelateItemFromBasket(item_id, quantity=1, refresh=0) {
   try {qt = parseInt(quantity);} catch (err) {qt=1;}
   try {qt = parseInt(refresh);} catch (err) {refresh=1;}
   promise = longclawclient.basketDetail.del({
      prefix: "/api/",
      urlParams: { id: item_id },
      queryParams: { quantity: qt }
   });
   promise.then(function(result) {
         console.log('succes');
      }, function(err) {
         console.log(err);
   });
   setTimeout(function () {
       RefreshCart();
   }, 30);
}

**Comment by JamesRamm** [comment]
Ok, what is the response you are getting?

**Comment by Wladislav** [comment]
I getting 'succes', but deleted only 1 product. In despite of quantity>1 in urlParams in my case

**Comment by JamesRamm** [comment]
Ok great. This requires a change in the front end client.
I've created a new issue for it: #130
