### ISSUE TITLE
pin wagtail version < 2.0

### ISSUE THREAD

**Issue by robvdl** [JamesRamm/longclaw#141]
* longclaw version: master
* Django version: 1.11
* Python version: 3.5

### Description

Wagtail 2 has been released and the imports have changed, e.g. "wagtail.wagtailcore" becomes "wagtail.core".

So longclaw isn't currently working if you install it, as it will install wagtail 2.0

Need to pin it wagtail>1.9,<2.0 in the requirements.txt to prevent it from pulling down wagtail 2.0 until longclaw is compatible.

**Comment by DanAtShenTech** [comment]
You're probably already aware of this, but Wagtail has some [commands to automatically update the module path references](http://docs.wagtail.io/en/latest/releases/2.0.html#wagtail-module-path-updates).  Just thought I'd point this out in case you weren't already aware and it might be of use to you.  Today I'm starting a Wagtail 2 site and after that will be doing a Longclaw site for the same customer, so I really need Longclaw to work with Wagtail 2.  Any ETA on this functionality?

**Comment by JamesRamm** [comment]
@robvdl 
Thanks for the issue and patch which I have merged.
Longclaw 0.x now pinned to Wagtail 1.x so closing this issue. A new tag/release will follow which will be the last release of 0.x. Longclaw 1 and on will support Wagtail/Django 2 only. 

@DanAtShenTech 
No ETA on Wagtail 2 support as of yet as development is proceeding when I have time/feel like it.
If your company needs professional support feel free to get in touch.
