### ISSUE TITLE
requestList is not defined in orders.bundle.js

### ISSUE THREAD

**Issue by linuxluigi** [JamesRamm/longclaw#164]
* longclaw version: 0.2.1
* Django version: 1.11.13
* Python version: 3.6

### Description

When select a Order in the Wagtail Admin it shows in the JavaScript log `ReferenceError: requestList is not defined` from orders.bundle.js and it shows a empty Order View

<img width="647" alt="error message" src="https://user-images.githubusercontent.com/8136842/40040749-c24c5a52-581b-11e8-8cd8-032b9e37505d.png">

<img width="845" alt="wagtail-admin order view" src="https://user-images.githubusercontent.com/8136842/40041012-dc0b1a2c-581c-11e8-9a93-008765e7f60c.png">

**Comment by SamuelM333** [comment]
Same issue using the longclaw_demo when trying to interact with the basket.

```
VM4705 longclawclient.bundle.js:339 Uncaught ReferenceError: requestList is not defined
    at Object.<anonymous> (VM4705 longclawclient.bundle.js:339)
    at __webpack_require__ (VM4704 vendors.bundle.js:72)
    at Object.<anonymous> (VM4705 longclawclient.bundle.js:14)
    at Object.<anonymous> (VM4705 longclawclient.bundle.js:15)
    at __webpack_require__ (VM4704 vendors.bundle.js:72)
    at Object.<anonymous> (VM4705 longclawclient.bundle.js:5)
    at __webpack_require__ (VM4704 vendors.bundle.js:72)
    at webpackJsonpCallback (VM4704 vendors.bundle.js:43)
    at VM4705 longclawclient.bundle.js:1
```

**Comment by SamuelM333** [comment]
@linuxluigi Have you found any workarounds for this? Maybe using an older version of longclaw?

**Comment by linuxluigi** [comment]
hmm maybe I found something

```js
//List/Post new product request
var requestsList = exports.requestsList = new ApiEndpoint('requests/');
//List product requests for a single variant
var requestVariantList = exports.requestVariantList = new ApiEndpoint('requests/variant/{id}/');

exports.default = {
  orderDetail: orderDetail, fulfillOrder: fulfillOrder, refundOrder: refundOrder, checkout: checkout,
  checkoutToken: checkoutToken, basketList: basketList, basketListCount: basketListCount,
  basketDetailCount: basketDetailCount, basketDetail: basketDetail, shippingCost: shippingCost,
  shippingCountries: shippingCountries, shippingCountryOptions: shippingCountryOptions,
  addressList: addressList, addressDetail: addressDetail, requestList: requestsList, requestVariantList: requestVariantList
};
```

It looks like `requestList: requestList` should be `requestList: requestsList` than it workes fine. And the var `requestsList` was init but never used bevor.

**Comment by SamuelM333** [comment]
@linuxluigi Yeah the issue is here `longclaw/client/src/api/api.js` line 267. Changing `requestList: requestList` to `requestList: requestsList` just like you said solves the issue. Gonna open a pull request to fix this.

![julie-bakes-samuelm333 c9users io_admin_longclaworders_order_detail_1_](https://user-images.githubusercontent.com/13484197/40820912-d0bee4a8-6539-11e8-9946-a263b3b4d11e.png)

**Comment by JamesRamm** [comment]
Thanks for this fix. I will begin preparing a 0.2.2 release with the latest bug fixes.

**Comment by Kuntal-KK** [comment]
Is this issue fixed? because I am still getting that error..
