### ISSUE TITLE
longclawclient is not defined

### ISSUE THREAD

**Issue by bumbleshet** [JamesRamm/longclaw#165]
* longclaw version: 0.2.1
* Django version: 1.11.13 
* Python version: 2.7

I loaded the tag {% longclaw_client_bundle %} and rendered the button {% add_to_basket_btn variant.id btn_text="Add To Basket" btn_class="btn btn-success" %}. My problem is whenever I click the "Add to Basket" button, an error will occur on the console "ReferenceError: longclawclient is not defined". I raised this error because I can't pass the data on basket.html.

**Comment by JamesRamm** [comment]
There is a possibility the JS is missing, are you able to try running `longclaw build` (requires npm)?

**Comment by bumbleshet** [comment]
Yes but then there's this requestList error on the console
