### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by bumbleshet** [JamesRamm/longclaw#167]
* longclaw version: 0.2.1
* Django version: 1.11.13
* Python version: 2.7

### Description

quantity = request.data.get("quantity", 1) returns unicode instead of int. This happened when I passed quantity to DELETE <api_prefix>/basket/<variant_id>

**Comment by daemondazz** [comment]
Python 3.5.2
longclaw==0.2.1
Django==1.11.13

I am also seeing a similar error both trying to increment and decrement the basket item quantity when specifying the quantity in the POST/DELETE.


```
  File "/home/project/lib/python3.5/site-packages/longclaw/longclawbasket/api.py", line 80, in destroy
    item.decrease_quantity(quantity)
  File "/home/project/lib/python3.5/site-packages/longclaw/longclawbasket/models.py", line 37, in decrease_quantity
    self.quantity -= quantity
TypeError: unsupported operand type(s) for -=: 'int' and 'str'
```

**Comment by JamesRamm** [comment]
I believe 5db44a3 fixes this; thanks @bumbleshet
