### ISSUE TITLE
Development project?

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#17]
Developing longclaw requires setting a django project wagtail to run longclaw within...I wonder if we can make it simpler to setup for development by providing a dev project in the repo somehow?

Are there any django app development guidelines on this?

**Comment by JamesRamm** [comment]
I think the best thing to do here is to create a demo site (external to the longclaw codebase) and scripts within longclaw to get setup. 
Something similar to: https://github.com/wagtail/wagtaildemo/

**Comment by alexfromvl** [comment]
Option with a demo site perfect solution. I like how it is implemented in Django-oscar - demo site unfolds command: make sandbox.

Sample code Django-oscar:
$ git clone https://github.com/django-oscar/django-oscar.git
$ cd django-oscar
$ mkvirtualenv oscar  # needs virtualenvwrapper
(oscar) $ make sandbox
(oscar) $ sandbox/manage.py runserver

**Comment by JamesRamm** [comment]
@alexfromvl 
#21 has made it possible to setup a longclaw project with `django-admin startproject` by providing the project template. I think this could be sophisticated enough (for now) to close this issue, how about you?

To be clear, it does not give you a full featured shop like the django-oscar sandbox, but provides the same basic templates as `wagtail start mysite`, plus the product/product_index templates you supplied and an empty, custom `ProductVariant` implementation. 

For a future issue, if we wanted a more fully featured demo site, we could do something similar to wagtail:
https://github.com/wagtail/wagtaildemo
?

**Comment by Johnstone-Tech** [comment]
+1 for a fully featured demo. 

suggest a new repo, longclaw-demo.

I have been implementing a longlaw site to hack on and found my self wondering what produts to model for testing purposes, i feel a demo site would add great value if it can take advantage of the current featureset. Oscar [[no longer](https://github.com/django-oscar/django-oscar/commit/51980c748463d14f82295b6ad349f8cfa47580f2) ships with a working demo as they found it hard to keep the demo up to date with thier own package. That in itself is rather worrying so i think its worth putting some time int thinking about the type of shop you want to model so that you can show off features etc.

**Comment by JamesRamm** [comment]
I will move a demo site forward to being a blocker for a 0.1.0 release as it is growing in importance. 

In terms of what products to model I think something along the lines of fashion (e.g. a shop selling t-shirts), music (Product is an album, variants could be CD or Vinyl (digital download might be a bit much at this point) or books. They would be fairly easy to implement right now and are pretty relatable & straightforward to understand. 

In terms of keeping it up to date with longclaw, I think the philosophy of longclaw will differ in 2 key areas to Oscar:

- Longclaw aims to be minimal and leave as much front-end design as possible up to the developer. 
- Longclaw has Wagtail behind it..this should make maintenance and stability of longclaw (in the long run) easier. Wherever possible Longclaw will use existing Wagtail features. We dont have a big admin backend to design and maintain, since Wagtail will do that for us :) 
I hope this will make it easier to maintain a demo site. 
At the moment longclaw is of course far less complex and feature rich than Oscar (I intend for it to remain as simple as possible) but it will grow somewhat.

**Comment by JamesRamm** [comment]
Unless there are alternate suggestions or preferences, I think Ill go ahead and make the demo a t-shirt shop.
Demo repo is here: https://github.com/JamesRamm/longclaw_demo

**Comment by JamesRamm** [comment]
Although on second thoughts, creating it as a music shop offers the opportunity to add digital downloads if/when longclaw offers any kind of support for that. (Getting hold of some stock images also seems easier for some reason...)

**Comment by Johnstone-Tech** [comment]
Music shop is a good idea, theres a lot of metadata assoiciated with albums, artisit i feel this may be usefull when demos certain features in the future. Do you know if any of the other django shop framweorks have digital products as a feture?

**Comment by JamesRamm** [comment]
I dont know of any shop which offers support for storage & delivery of digital products. I think in Oscar you can certainly _model_ a digital product.

I see digital products being a 0.2 or later release. There would be a number of things to consider (marking products as shippable/not shippable, I imagine #10 would be needed first - and perhaps further work on emails etc).
Perhaps some initial support for modelling a digital product in 0.2 and some kind of cool support for automating delivery and other niceties in a future 1.0 release...

**Comment by JamesRamm** [comment]
Since the demo site is up and (mostly) fully functional at https://github.com/JamesRamm/longclaw_demo/ I'm going to close this issue. Future enhancements/bugs on the demo site should now be raised at https://github.com/JamesRamm/longclaw_demo/issues/
