### ISSUE TITLE
Empty country list while creating a Shipping rate

### ISSUE THREAD

**Issue by SamuelM333** [JamesRamm/longclaw#173]
* longclaw version: 0.2.1
* Django version: 1.11.13
* Python version: 3.6

### Description
While adding a Shipping rate in the Wagtail admin, the country list is empty and there's no apparent way of adding one. I had to add to create an `admin.py` file and register `longclaw.longclawshipping.models.Country`, then add a country manually in the Django admin.

I believe this list should be pre-populated with country options or at least offer an inline panel in the Shipping rate panel. 

![screenshot_2018-06-02_19-31-31](https://user-images.githubusercontent.com/13484197/40881412-5d238c24-669c-11e8-93bf-b3d69fd646c3.png)

**Comment by JamesRamm** [comment]
Normally you would run `loaddata` with the shipping data JSON file provided in longclaw shipping.
In longclaw 1.0 a helper command - `load-countries` - is included. A setup would be something like:
```
longclaw start my_project
longclaw load-countries
```
