### ISSUE TITLE
Checkout and basket templates

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#2]
The checkout and basket apps are currently written as a REST api, the primary motivation being that it allows total customisation of how you integrate it into your website (I was thinking react apps and nice popup modals for easy checkouts). 

It would also be useful to provide generic views and templates for separate-page checkouts/basket views.

**Comment by alexfromvl** [comment]
Given that the project is aimed at creating a universal application, in the initial stage it is necessary to provide an alternative for test order. So as of now to launch a project to set up an applications stripe-payments and braintree-payments.

**Comment by JamesRamm** [comment]
I think I understand what you are saying - at the moment you would require a braintree, paypal or stripe account in order to test the payments and what we need is a dummy backend? I agree - Ive raised an issue to track this specifically: #6

**Comment by JamesRamm** [comment]
@alexfromvl...reading over your comment again, perhaps I have misunderstood originally and this issue is actually close to what you meant: #36

**Comment by alexfromvl** [comment]
@JamesRamm Those changes that you made initially helped to solve the issue of the setting without having to register accounts braintree, paypal or stripe.

Given the development of the project, it will be optimal to transfer the payment settings in the basу.py

With the choice of: for the test environment is disabled, for the finished site is enabled (using the token)

**Comment by JamesRamm** [comment]
On master now there are generic django views for basket & checkout, plus a checkout template in the `project_template` which tries to explain and help with some of the more tricky details. I think this is enough to sufficiently close this issue and we can narrow down further problems in more specific issues later on.
