### ISSUE TITLE
Fixture 'shipping_initial' is missing

### ISSUE THREAD

**Issue by 5in4** [JamesRamm/longclaw#224]
* longclaw version: 1.0.0
* Django version: 2.1.7
* Python version: 3.7.2

## Description

After setting up longclaw according to the documentation (https://jamesramm.github.io/longclaw/docs/tutorial/install#migration), the management command 'loadcountries' fails.

`./newproject/manage.py loadcountries`
`CommandError: No fixture named 'shipping_initial' found.`

**Comment by JamesRamm** [comment]
Somehow json files were excluded from the tarball. I've pushed a fix and will make a bug release asap. 
For a workaround you can manually add the folder shipping/fixtures to your longclaw installation

**Comment by JamesRamm** [comment]
Oops! I forgot I had fixed but not released. I'll make a 1.0.1 release today

**Comment by edu2004eu** [comment]
@JamesRamm kind reminder here :)

**Comment by JamesRamm** [comment]
:face_with_head_bandage:  I'm terrible. It is done.
