### ISSUE TITLE
Project setup CLI

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#23]
Idea is to provide a CLI, much the same as wagtails' `wagtail start my_project` but using the longclaw template.

Running `django-admin startproject --template ...` can be a bother when you need to figure out where the longclaw directory is (especially when using virtual environments)

**Comment by alexfromvl** [comment]
Need add requirements.txt in create folder new mysite, after command - longclaw start mysite.

**Comment by JamesRamm** [comment]
@alexfromvl running `longclaw start mysite` gives a folder structure like:

    mysite/
        home/
        products/
        search/
        mysite/
        manage.py
        requirements.txt

I.e. with `requirements.txt` in the top level folder. Is this what you mean?

**Comment by alexfromvl** [comment]
Checked several times in different versions of the python and different virtual environments - it always creates a folder without the file requirements.txt.

Here's what's in the folder after the command: longclaw start mysite
```
mysite/
    home/
    products/
    search/
    mysite/
    manage.py
```

However, in the original project(https://github.com/JamesRamm/longclaw), I see that there is a file requirements.txt
