### ISSUE TITLE
Deploying longclaw with wsgi.py in cPanel

### ISSUE THREAD

**Issue by TenzoNakami** [JamesRamm/longclaw#237]
* longclaw version: 1.0.2
* Django version: default from longclaw as I only do pip install longclaw
* Python version: 3.6.8

## Description

I'm trying to deploy Longclaw to my new shared python hosting. But they only allow us to do everything from cPanel (no ssh access whatsoever). Everytime I installed longclaw, setup the wsgi deployment and editing the bash profile (they uses virtualenv, therefore we need to setup the bash profile), longclaw will not start whatsoever. For worse, there is no logs so I can't really tell what is wrong. I did start a project from longclaw, I did changed the database in base.py to what my database currently is, and whenever I tried to access the website it will only show the file directory (the hosting uses litespeed, therefore litespeed is shown as opposed to longclaw).

Are there any documentation on how to deploy longclaw properly? I can deploy wagtail without problem. I can deploy django without problem, but longclaw just wont start.

**Comment by JamesRamm** [comment]
Hi
Running longclaw is no different from any django website - can you explain how you are running wsgi.py & did you make any changes?

**Comment by JamesRamm** [comment]
@TenzoNakami 
Closing as I dont have enough info to reproduce or fully understand the problem.
Feel free to reopen with more info.
