### ISSUE TITLE
Wrong Requirements for wagtail in requirements.txt

### ISSUE THREAD

**Issue by bmoe872** [JamesRamm/longclaw#246]
## Current Setup

* longclaw version: 1.0.2
* Django version: 2.1.10
* Python version: 3.5.2

## Description
Longclaw's requirements.txt says it needs `wagtail>=2.3`, however this is incorrect as currently longclaw depends on a migration found in `wagtail==2.4`, the specific migration is:
`wagtailcore.0041_group_collection_permissions_verbose_name_plural`

## Solution
Change the requirements.txt to be `wagtail>=2.4`

**Comment by JamesRamm** [comment]
Thanks for that catch!
