### ISSUE TITLE
detail_route has been deprecated from DRF 3.8: Cannot import name 'detail_route' from 'rest_framework.decorators' 

### ISSUE THREAD

**Issue by fedonkin** [JamesRamm/longclaw#262]
ImportError: cannot import name 'detail_route' from 'rest_framework.decorators' (\longclaw\thcr_l\lib\site-packages\rest_framework\decorators.py)

* longclaw version:  1.0.2
* Django version: 2.2.6
* Python version: 3.7

Its because detail_route has been deprecated from DRF 3.8. You can check their change-log as well. Alternatively, you can use action decorator. 
For example:

```
from rest_framework.decorators import action

@action(detail=True, methods=['post'])
def set_password(self, request, pk=None):
   ....
```

https://www.django-rest-framework.org/community/3.8-announcement/#action-decorator-replaces-list_route-and-detail_route

**Comment by fedonkin** [comment]
longlaw\orders\api.py:


```
    @action(detail=True, methods=['post'])
    def refund_order(self, request, pk):
        """Refund the order specified by the pk
        """
        order = Order.objects.get(id=pk)
        order.refund()
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(detail=True, methods=['post'])
    def fulfill_order(self, request, pk):
        """Mark the order specified by pk as fulfilled
        """
        order = Order.objects.get(id=pk)
        order.fulfill()
        return Response(status=status.HTTP_204_NO_CONTENT)
```


longlaw\basket\api.py:

```
    @action(detail=False, methods=['get'])
    def total_items(self, request):
        """
        Get total number of items in the basket
        """
        n_total = 0
        for item in self.get_queryset(request):
            n_total += item.quantity

        return Response(data={"quantity": n_total}, status=status.HTTP_200_OK)

    @action(detail=True, methods=['get'])
    def item_count(self, request, variant_id=None):
        """
        Get quantity of a single item in the basket
        """
        bid = utils.basket_id(request)
        item = ProductVariant.objects.get(id=variant_id)
        try:
            count = BasketItem.objects.get(basket_id=bid, variant=item).quantity
        except BasketItem.DoesNotExist:
            count = 0
        return Response(data={"quantity": count}, status=status.HTTP_200_OK)
```

**Comment by thenewguy** [comment]
I think this is fixed in master. Use the appropriate package versions for the longclaw release you've installed

**Comment by JamesRamm** [comment]
This is fixed in master and unfortunately DRF is not pinned in earlier versions. You can either install from master (pip install git+git://github.com/JamesRamm/longclaw.git ) or explicitly install DRF <= 3.8

**Comment by jghyllebert** [comment]
I just ran into this on a fresh setup. Might be good to either document this in docs or push a new version to pypi to prevent this error.

**Comment by JamesRamm** [comment]
@jghyllebert 
Yes I think a 1.0.3 release is needed. I'll try to get this out tonight.
