### ISSUE TITLE
'MaxValueValidator' is not defined

### ISSUE THREAD

**Issue by fedonkin** [JamesRamm/longclaw#263]
I do according to the instruction, https://jamesramm.github.io/longclaw/docs/tutorial/products
gives an error:
`name 'MaxValueValidator' is not defined`
Swears at it:
`discount_percent = models.PositiveSmallIntegerField(default=20, validators=[MaxValueValidator(75)])`\

**I do not understand how to fix :(**
heeelp

longclaw version: 1.0.2
Django version: 2.2.6
Python version: 3.7

**Comment by thenewguy** [comment]
Check the requirements of the longclaw version you've installed. It will tell which version of Django is supported.

**Comment by thenewguy** [comment]
Or provide more code so we can see what your problem is.  Did you just copy and paste? You have to import the validator from Django

**Comment by fedonkin** [comment]
Yes, copied and pasted. Is there an example of how to import a validator from django?

**Comment by fedonkin** [comment]
> Or provide more code so we can see what your problem is. Did you just copy and paste? You have to import the validator from Django

Yes, copied and pasted. Is there an example of how to import a validator from django?

**Comment by thenewguy** [comment]
This project is an extension of Django and wagtail.  To use it effectively you must have good working knowledge of both.  I suggest you familiarize yourself with their respective tutorials.

Reference https://docs.djangoproject.com/en/2.2/ref/validators/ for your question about validators

**Comment by fedonkin** [comment]
> Этот проект является продолжением Django и трясогузки. Чтобы использовать его эффективно, вы должны иметь хорошие рабочие знания обоих. Я предлагаю вам ознакомиться с их соответствующими учебниками.
> 
> Ссылка https://docs.djangoproject.com/en/2.2/ref/validators/ на ваш вопрос о валидаторах

Спасибо!
Так правильно?
```
    def MaxValueValidator(value):
        if value < 75

    discount_percent = models.PositiveSmallIntegerField(
        default=20,
        validators=[
            MaxValueValidator
        ]
    )
```

**Comment by thenewguy** [comment]
Hrm, I cannot understand most of that. English please if possible.

But, the code you provided is incorrect.  Django provides the MaxValueValidator out of the box.  You just need to import it before you use it... hence the python NameError (https://docs.python.org/2/library/exceptions.html#exceptions.NameError).  This isn't a longclaw issue.

```
from django.core.validators import MaxValueValidator
```

**Comment by fedonkin** [comment]
> Hrm, I cannot understand most of that. English please if possible.
> 
> But, the code you provided is incorrect. Django provides the MaxValueValidator out of the box. You just need to import it before you use it... hence the python NameError (https://docs.python.org/2/library/exceptions.html#exceptions.NameError). This isn't a longclaw issue.
> 
> ```
> from django.core.validators import MaxValueValidator
> ```
🤗 Oh, thank you very much.

**Comment by JamesRamm** [comment]
@fedonkin Did this solve your issue? Please close if so.
