### ISSUE TITLE
CSS changes to order detail view

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#38]
Make the fulfillled/unfulfilled status stand out a bit more & improve spacings in buttons...something like this:

![image](https://cloud.githubusercontent.com/assets/2784823/23847756/d403b6e2-07cb-11e7-909c-dac82dbfeebb.png)

(use green for fulfilled orders)

Other changes:
- Email should be an 'email' link
- Currency symbol on the prices

**Comment by alexfromvl** [comment]
I suggest using the class:
<span class="button warning" style="padding-top: 8px;">UNFULFILLED&nbsp;</span>

This will make the desired selection when the status changes before updating the class:
<span class="button yes" style="padding-top: 8px;"><font><font class="">FULFILLED&nbsp;</font></font></span>

If the solution suits, then I will do PR

**Comment by JamesRamm** [comment]
That seems like it would be ok.

**Comment by alexfromvl** [comment]
add #64

**Comment by JamesRamm** [comment]
this was closed by #64
