### ISSUE TITLE
Decimal in price_range (Product Models)

### ISSUE THREAD

**Issue by alexfromvl** [JamesRamm/longclaw#39]
When you try to display a product page, the price appears (Decimal('100.00'), Decimal('100.00')).
I address the price in the page template via variable {{ page.price_range }}.
What could be the problem? How to output only numbers?

**Comment by JamesRamm** [comment]
``price_range`` is the min and max prices of all the product variants, use ``{{ page.price_range.0 }}`` and ``{{ page.price_range.1 }}`` to access the min/max price.
To access the price of individual product variants, you can do:
```
{% for variant in page.variants.all %}
{{ variant.price }}

{% endfor %}
```
If you know you only have 1 product variant, you can go straight to it, I think either ``{{ page.variants.0.price }}`` or ``{{ page.variants.all.0.price }}`` should do it (you'll need to check the django docs here..)

**Comment by alexfromvl** [comment]
Thanks, works perfectly this version:

```
{% for variant in page.variants.all %}
    {{ variant.price }}
{% endfor %}
```
