### ISSUE TITLE
Django-payments or continue developing own?

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#4]
Payments are currently handled in the `checkout` app. They are:

- Very loosely coupled. Nothing about the payment is stored in the database, instead trusting the payment backend to keep all relevant details. An new `Order` instance is created upon successful payment which contains all the order related details (essentially, what products and shipping address)
- Easily extendable. All that is required is a class implementing the correct interface
- Supports only Stripe, Braintree and Paypal VZero (through the braintree package)
- Doesn't support refunds
- Fairly fragile (needs testing & development).

We could potentially use django-payments as a more mature backend rather than continuing to develop our own, however, this requires a separate db model which most likely duplicates info in the order model and/or stores unnecessary info. It also has fairly low levels of activity but 20 odd outstanding issues...

**Comment by Johnstone-Tech** [comment]
I have not gotten longclaw fuctioning as yet, However during my experimentation i noticed that there is no mention of a few additional libraries required , specifically related to payments, 'braintree' and 'stripe' packages. Is it worth adding to the docs now or wait until a decision has been made on this issue.

**Comment by JamesRamm** [comment]
@Johnstone-Tech you are absolutely right - since there is this functionality, I should add some docs on the additional libraries required and have raised this in #20.

With regards to getting longclaw functioning - if you are having problems getting it setup (I am certain that is not yet easy to get it going for anyone but me - it has been very much a personal wip so far), please go ahead and raise an issue detailing whats going on. This will help a great deal in flagging up what improvements are needed and what can be done to make it easy to setup.

**Comment by JamesRamm** [comment]
@Johnstone-Tech I have expanded #20 to be a general setup issues/dependencies issue, so would welcome any comments you have re. problems setting up longclaw there

**Comment by JamesRamm** [comment]
According to https://djangopackages.org/grids/g/generic-payment-interfaces/ django-payments does not support python 3, which basically answers the question for us.
