### ISSUE TITLE
Basket api

### ISSUE THREAD

**Issue by Johnstone-Tech** [JamesRamm/longclaw#44]
* longclaw version: 0.1.0
* Django version: 1.10.6
* Python version: 3.6.0
* Operating System: Linux (arch)

### Description

Attempting to hack on the basket templates and api but seem to be unable to reach the api urls.

### What I Did

I have tried sending POST and GET Requests to the few api commands that i felt i could use without having items in a basket yet. Im getting 404 errors.

from what i can tell the api url is just `/api/` so the format of the url i am sending data to is `localhost:8000/api/add_to_basket/`

I have attached some of the command history from httpie tool
```
http://localhost:8000/products/> cd pencil/
http://localhost:8000/products/pencil/> get
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Date: Wed, 29 Mar 2017 10:34:40 GMT
Server: WSGIServer/0.2 CPython/3.6.0
Set-Cookie:  csrftoken=ong9dNCJnKzs4X9DwkFDW36jRU5dyGbs45pd6rrCndOBO7qmk4UvPk9xGB2PV8W1; expires=Wed, 28-Mar-2018 10:34:40 GMT; Max-Age=31449600; Path=/
Vary: Cookie
X-Frame-Options: SAMEORIGIN

AttributeError: 'unicode' object has no attribute 'items'

Parse tree:
<Node called "action" matching "get">  <-- *** We were here. ***
    <RegexNode called "_" matching "">
    <Node called "method" matching "get">
        <RegexNode matching "get">
    <RegexNode called "_" matching "">
    <Node matching "">
    <Node matching "">
    <Node matching "">
    <RegexNode called "_" matching "">
http://localhost:8000/products/pencil/> cd /api/add_to_basket/
http://localhost:8000/api/add_to_basket/> X-CSRFToken:ong9dNCJnKzs4X9DwkFDW36jRU5dyGbs45pd6rrCndOBO7qmk4UvPk9xGB2PV8
W1
http://localhost:8000/api/add_to_basket/> post
HTTP/1.0 404 Not Found
Content-Type: text/html
Date: Wed, 29 Mar 2017 10:35:24 GMT
Server: WSGIServer/0.2 CPython/3.6.0
Vary: Cookie
X-Frame-Options: SAMEORIGIN

http://localhost:8000/api/add_to_basket/> 

```

**Comment by JamesRamm** [comment]
404 is unexpected, it suggest perhaps the longclaw urls are not registered? Have you setup the site using the longclaw project template (``longclaw start``) or otherwise included the longclaw URLs?

As a minimum ``add_to_basket`` should be passed ``variant_id`` in the request data. ``quantity`` can also be passed. 

Some example JS I am using in my site (uses ``fetch``)::

    const csrf = JsCookie.get('csrftoken');
    fetch(
    '/api/add_to_basket/'
    {
      method: 'POST',
      headers: {
          Accept: 'application/json, application/json, application/coreapi+json',
         'Content-Type': 'application/json',
         'X-CSRFToken': csrf
      },
      credentials: 'include',
      body: JSON.stringify({ variant_id: 1 })
    })
       .then(...)

I will have a poke around with httpie and try to post an example. 
The DRF interface is enabled, so you should be able to navigate to e.g. http://localhost:8000/api/add_to_basket/ to verify the URL is actually there.

If you want to change the prefix for the API urls, you can set ``API_URL_PREFIX`` in your settings.

**Comment by Johnstone-Tech** [comment]
I noticed you were using the django_rest_framework and that i should see the DRF Interface and im not on any of the api urls so i must have something wrong with my setup. I created this particular instance using the provided `longclaw start`. I will recreate my test project see if i can spot where i went wrong.

**Comment by Johnstone-Tech** [comment]
Okay so i have just tried to replicate the issue and i believe it may be with the project generated by ~longclaw start~, though I will have to integrate longlclaw into a base wagtail project to verify.

I have longclaw 0.1.0 installed in a local virtualenv.

`longclaw start claw` project is created.
`./manage.py migrate` make migrations and apply.
`../manage.py createsuperuser` - create superuser
`./manage.py runserver` run dev server on port 8000

server is running fine and display homepage template.

try to access any of the api urls and i get a 404.

I can verify that the project urls does seem to be importing the longlaw urls below

```urlpatterns = [
    url(r'', include(basket_urls)),
    url(r'', include(checkout_urls)),
    url(r'', include(shipping_urls)),
    url(r'', include(order_urls)),
]
```

**Comment by JamesRamm** [comment]
Ok
I will compare the longclaw template with the setup for my own (working) project. I'll also setup the demo project (#17) which should highlight any issues to me

**Comment by JamesRamm** [comment]
@Johnstone-Tech 
Ok this is definitely a problem. 
There are 2 things that need to be done which are not in the project template:

- `'rest_framework'` needs to be added to the `INSTALLED_APPS` in your django settings
- The longclaw URL's need to come *before* wagtail urls in your `urls.py`. I.e It should look something like:
```python
    urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    url(r'', include(longclaw_urls)),
    url(r'', include(wagtail_urls))    
]
```

These are both currently neglected in the project template, so I will sort that out. I need to do further testing to make sure there arent any other related issues, but this should be get you up and running with testing the API.

**Comment by Johnstone-Tech** [comment]
@JamesRamm That did the trick, adding `rest_framework` and switching order of urls in settings.py got me going.

**Comment by JamesRamm** [comment]
Great. I'll close this. 
I have a slight concern about the ordering of installed apps (specifically whether the users `products` app should come before some longclaw apps), but I have not come across any issue yet in the demo project.
