### ISSUE TITLE
Basket API more RESTful

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#46]
Basket API urls are currently:

`add_to_basket/`
`remove_from_basket/`
`get_basket/`
`basket_total_items/`
`get_item_count/`

These could be better expressed as:

`basket/` - Accepts GET and POST requests (as replacement for `get_basket` and `add_to_basket`)
`basket/count/` - Accepts GET (`basket_total_items`)
`basket/(?P<variant_id>[0-9]+)/` - Accepts GET and DEL requests (`remove_from_basket`)
`basket/(?P<variant_id>[0-9]+)/count/` - Accepts GET (`get_item_count`)

**Comment by JamesRamm** [comment]
@Johnstone-Tech
Just making you aware of this since you mentioned hacking around with the basket api. I'm planning to push these changes in the next few days.

**Comment by Johnstone-Tech** [comment]
@JamesRamm Thanks for the heads up, these changes to the urls will make for a clean api. :)
