### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by Johnstone-Tech** [JamesRamm/longclaw#48]
What do you think about having an IRC Channel for communication amongst developers. There has been a few things i wanted to ask @JamesRamm, but don't feel its worth filing an issue. Doesn't have to be IRC of course, Slack, Mattermost or email but im sure wed all rather not have any more email coming in.

**Comment by JamesRamm** [comment]
Good idea. I have created a channel on freenode at #longclaw

I'm no IRC expert so forgive any initial fumblings....

**Comment by JamesRamm** [comment]
If there are no objections I might just switch to slack. I originally held off as I thought you needed to register to use it and that could be a pain for non slack users, but now I see that is not the case..

**Comment by JamesRamm** [comment]
I have created a slack channel for now...
https://longclaw-wagtail.slack.com

**Comment by Johnstone-Tech** [comment]
I have not used slack before, does it require an invitation to join the channel.

**Comment by JamesRamm** [comment]
Yes it seems to...there are ways around, but freenode seems less bother!!
Circle round again...

So, the IRC channel is on freenode and is #longclaw

**Comment by JamesRamm** [comment]
http://webchat.freenode.net/?channels=longclaw&uio=d4

**Comment by JamesRamm** [comment]
@Johnstone-Tech 
Are you able to connect to the IRC channel so we can check all is ok?

**Comment by Johnstone-Tech** [comment]
Yes the channel is listed on freenode and i am able to connect, I have sent you a message to verify. My nick is Sud0x3.
