### ISSUE TITLE
Product requests

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#49]
### Description

On my own site (at http://104.236.209.115/) I have functionality to allow customers to request/register interest in products that are out of stock. 

It is easily enabled by adding a `request_count` field to the `ProductVariant` and adding an api endpoint to augment it. 

If there is interest this could be incorporated into longclaw. I would imagine it actually being a separate model so we can record the date of each request (and potentially other fields - user or ip etc..)

**Comment by Johnstone-Tech** [comment]
I think this is a great idea, more so for smaller shops that may be self manufacturing, they may want to make them to order rather than make them in advanced. Those boards on your shop look interesting, something to do with audio?

**Comment by alexfromvl** [comment]
This is the required functionality. Perhaps to version 0.2.0 it is worth thinking about the reactivation of user registration with the addition of a personal client cabinet.

**Comment by JamesRamm** [comment]
@Johnstone-Tech yes ... DIY boards for audio recording gear... :smile: 

@alexfromvl I think accounts for customers is going to require a number of tickets to properly fulfil. It is definitely something I want to do but I am wary of piling too many issues against v0.2; v0.3 might be more realistic. When 0.1 is out I will raise some issues against what I think the key areas for this work are. Wagtail already integrates django users & groups into the admin so we will need to make sure we utilise this.

**Comment by JamesRamm** [comment]
515a23c adds a 'productrequests' app to address this issue. 
Some notes:

- Optional app, so has gone under a ``contrib`` sub-package and explicitly no dependency on it from the rest of longclaw
- Has an API and a templatetag which adds in a very basic 'make request' button for a given variant id 

I have yet to work out how best to display requests in the admin, while keeping the constraint that the app is optional.

If anyone has any ideas about how they would like to see requests (as a separate item in the admin menu? On product pages somehow? Something else?) let me know.
