### ISSUE TITLE
0.1 Release

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#54]
This issue is just to decide upon and iron out final details for a 0.1 release. 

Ideally I will have the demo site fully functional before releasing, though I am hoping to be not more than 1 week away. 

A few things that need ironing out:

- Would be great if there is anyone out there willing to have a look through the docs and raise issues against anything missing/nonsensical

- Docs need updating to reflect that longclaw can be installed from pypi (and the assets wont need building).
- Build and upload to pypi (I'll do this)
- Tag the master branch with the 0.1 release

- Any other requirements for a 0.1 release?

**Comment by Johnstone-Tech** [comment]
I will try to look over the documentation this weekend.

**Comment by Johnstone-Tech** [comment]
These changes will simplify how the docker image is built also so i wll do that once the package in on pypi.

**Comment by JamesRamm** [comment]
The installation doc updates for v0.1 are in the 0_1_docs branch, so there is really only the demo site to bring up to speed before releasing.

**Comment by JamesRamm** [comment]
Small update. The demo site is almost there, once https://github.com/JamesRamm/longclaw_demo/issues/7 is done I think 0.1 is good for release.

**Comment by alexfromvl** [comment]
I looked at the demo site. I think that the first version is ready for launch. In any case, this is an important step for the further development of the project.

**Comment by JamesRamm** [comment]
I just closed the remaining issues on the demo so will set up the release now

**Comment by JamesRamm** [comment]
Released.
Check #57 and #58 for immediate bugs. I think a 0.1.1 release might be warranted to clear these asap.

**Comment by JamesRamm** [comment]
I put out a 0.1.1 release to clear up those bugs since they block a successful longclaw deployment (without editing settings.py and potentially reinstalling django).

All looks good now! @alexfromvl and @Johnstone-Tech thanks for all your help! Hopefully this will get the ball rolling for 0.2.0....
