### ISSUE TITLE
Edit Cart 

### ISSUE THREAD

**Issue by osonwanne** [JamesRamm/longclaw#75]
- longclaw version: 0.1.1
- Django version: 1.10.7
- Python version: 2.7.1

### Description

I noticed using the longclaw_demo that you cannot edit the number of product items in cart, or remove/delete product items from cart. Please add these features.

**Comment by DanAtShenTech** [comment]
Could this issue be closed?

**Comment by JamesRamm** [comment]
@DanAtShenTech yes I think you are right.
Part of the request is related to longclaw_demo so I have opened an issue specifically for that here: https://github.com/JamesRamm/longclaw_demo/issues/13

If any further edit capabilities are required it can be addressed in separate issues
