### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by caputomarcos** [JamesRamm/longclaw#90]
beautifulsoup4==4.6.0
boto==2.45.0
certifi==2017.7.27.1
chardet==3.0.4
dj-database-url==0.4.1
Django==1.11.5
django-countries==4.6.1
django-dotenv==1.4.1
django-extensions==1.9.1
django-ipware==1.1.6
django-modelcluster==3.1
django-storages==1.5.2
django-taggit==0.22.1
django-tenant-schemas==1.9.0
django-treebeard==4.1.2
djangorestframework==3.6.4
html5lib==0.999999999
idna==2.6
longclaw==1.0.0
olefile==0.44
Pillow==4.2.1
psycopg2==2.6.2
pytz==2017.2
requests==2.18.4
six==1.10.0
Unidecode==0.4.21
urllib3==1.22
uWSGI==2.0.14
wagtail==1.12.1
wagtail-accessibility==0.1.2
wagtailfontawesome==1.0.6
webencodings==0.5.1
whitenoise==3.2.2
Willow==0.4

### Description

When I try to execute the Command longclaw in bash without parameters, I receive the follwing error message;

    ± |master {1} ?:1 ✗| → longclaw
    Traceback (most recent call last):
     File "/Volumes/containers/caputo.marcos/Projects/bakerydemo/env/bin/longclaw", line 11, in      <module>
       load_entry_point('longclaw==1.0.0', 'console_scripts', 'longclaw')()
     File "/Volumes/containers/caputo.marcos/Projects/bakerydemo/env/lib/python3.6/site-packages/longclaw-1.0.0-py3.6.egg/longclaw/bin/longclaw.py", line 71, in main
       args.func(args)
      AttributeError: 'Namespace' object has no attribute 'func'

**Comment by JamesRamm** [comment]
I'm not able to replicate this - looks like longclaw is installed from github master branch?

**Comment by caputomarcos** [comment]
Hi @JamesRamm yes, you're right! I'm using from master branch.

**Comment by JamesRamm** [comment]
Right, great I *can* recreate this installing from the master branch. 

Seems we have hit upon something like https://stackoverflow.com/questions/22990977/why-does-this-argparse-code-behave-differently-between-python-2-and-3

What is bizarre is this has never come up when running with `python setup.py develop` as I normally do. 

I'll do a bit more poking and try to get a fix. Right, great I *can* recreate this installing from the master branch. 

Seems we have hit upon something like https://stackoverflow.com/questions/22990977/why-does-this-argparse-code-behave-differently-between-python-2-and-3

What is bizarre is this has never come up when running with `python setup.py develop` as I normally do. 

I'll do a bit more poking and try to get a fix.

**Comment by JamesRamm** [comment]
@caputomarcos 
Does it now work for you?

**Comment by caputomarcos** [comment]
Yeap, It's ok now! thks @JamesRamm
